document.getElementById("bitnetLogo")?.addEventListener("click",function(){
    location.href="../main/main.html";
});
document.getElementById("aboutButton1")?.addEventListener("click",function(){
    location.href="../about/about.html"
})
document.getElementById("faqButton")?.addEventListener("click",function(){
    location.href="../faq/faq.html"
})
